plugins {
    id 'java'
    id 'maven-publish'
}

group = 'org.example'
version = '0.0.1-SNAPSHOT'
description = 'cint_common'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

jar {
    enabled = true
}

repositories {
    mavenCentral()
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // lombok
    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
    testCompileOnly 'org.projectlombok:lombok:1.18.46'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.46'
}

tasks.named('test') {
    useJUnitPlatform()
}
